department-for-transport-BODS/bods

transit_odp/fares_validator/constants.py
transit_odp/fares_validator/schema/fares_schema.json
transit_odp/fares_validator/views/functions.py
transit_odp/fares_validator/views/validators.py

Changes in this PR:
- FareFrame mandatory checks written into JSON schema
- Custom functions added into functions.py, along with constants updated
- Registered functions

Story/BODS-34-new: FareFrame mandatory validation checks

---

config/settings/base.py
poetry.lock
pyproject.toml
transit_odp/fares/templates/fares/review/success_content.html
transit_odp/fares/views/review.py

Before testing this, add a new flag called "is_fares_validator_active" from Django admin portal. Set it to Yes if fares validator needs to be called else, set to No.

Feature flag integration in publishing flow

---

transit_odp/fares_validator/tests/test_composite_functions.py
transit_odp/fares_validator/tests/test_product_type_checks.py

Change to composite function file and product type (FareFrame) checks file

story/BODS-56: Common lxml function change

---

transit_odp/api/tests/test_avl_api.py
transit_odp/api/views/avl.py

Improved logging around Consumer API requests

---

transit_odp/fares_validator/tests/test_validate_and_export.py

Test cases for validate get and set errors, and export excel

BODS-71 and BODS-69

---

transit_odp/avl/querysets.py
transit_odp/organisation/querysets.py
transit_odp/site_admin/exports.py
transit_odp/site_admin/tests/test_exports.py

moved the method *add_post_publishing_check_stats* in *DatasetQuerySet*
added new columns in the csv, and tested

BODP-5432: DFT Admin - Update to the datapublishing csv

---

transit_odp/site_admin/tasks.py
transit_odp/site_admin/tests/test_tasks.py

(temp data and deliverable reports)
Add in `task_delete_unwanted_data` delete method to clean the old data in PostPublishingCheckReport class.
By default the minimum days are:
1. DAILY: 28 days
2. WEEKLY: 90 days
Created new test cases

BODP-5457: Daily retention task to delete old data

---

transit_odp/fares_validator/csv.py
transit_odp/organisation/managers.py
transit_odp/organisation/models/organisations.py
transit_odp/organisation/querysets.py

This PR includes changes for:-
* Integration of new Fares Data Catalogue changes
* BODS-45
* Updated organisation querysets

story/BODS-45: New Fares Data Catalogue

---

transit_odp/publish/forms/seasonal_services.py

We now check that end date >= today

BODP-5734: Changed fields to date fields and added validator

---

transit_odp/avl/post_publishing_checks/daily/checker.py
transit_odp/avl/post_publishing_checks/daily/vehicle_journey_finder.py

Hi @anguskbell,
Could you please have a look at this PPC issue and suggest if the change I've done is good enough, please?

BODS-42 select recorded at time for txc xml file filteration

---

transit_odp/guidance/templates/guidance/bus_operators/overview.html
transit_odp/guidance/templates/guidance/bus_operators/who_publish_data.html

Includes these two ticket changes:
[BODS-12](https://kpmgengineering.atlassian.net/browse/BODS-12)
[BODS-13](https://kpmgengineering.atlassian.net/browse/BODS-13)

story/BODS-12&13: Text updates on screens

---

transit_odp/avl/tests/test_tasks.py
transit_odp/organisation/tests/csv/test_organisations.py
transit_odp/organisation/tests/test_updaters.py
transit_odp/publish/tests/test_views.py

Fixed org data catalogue test cases
Fixed email notification deletion test cases

BODS-312 fix failing test cases

---

transit_odp/api/tests/test_api_feed.py
transit_odp/api/tests/test_fares_api.py
transit_odp/api/views/fares.py
transit_odp/api/views/timetables.py

Link to the JIRA story:
[BODS-311](https://kpmgengineering.atlassian.net/jira/software/c/projects/BODS/boards/1664?modal=detail&selectedIssue=BODS-311)
This PR includes:-
* Changes to the timetables and fares APIs
* Updated and new test cases for the API changes

story/BODS-311: Remove inactive datasets from API responses for blank default status query param

---

transit_odp/browse/templates/browse/disruptions/download_disruptions.html
transit_odp/browse/templates/browse/downloads.html

Minor front end tweaks to wording on disruptions download pages

made minor front end tweaks to wording

---

transit_odp/fares/netex.py
transit_odp/fares/tasks.py

--Removed changes from DEV - related to test better memory management for Fares publishing.

fix/BODS-788: removing temporary changes

---

transit_odp/changelog/templates/changelog/snippets/release_notes.html
transit_odp/guidance/templates/guidance/developer/api_reference.html
transit_odp/static/openapi/fares.yml
transit_odp/static/openapi/timetables.yml

Adds release notes to release_notes.html
Updated fares and timetables api references
Updated api_reference.html to cover the same as the swagger changes.

Updated with text changes in BODS-172 and -1758

---

transit_odp/publish/requires_attention.py
transit_odp/timetables/csv.py
transit_odp/timetables/tests/test_csv.py

changes to evaluate 12 months old stale status using new rules

changes to evaluate 12 months old stale status using new rules

---

transit_odp/common/templatetags/filters.py

Testing instructions
- Publish a timetable and view the data quality score in the review page
- Access below page and verify the data quality score
Publish endpoint -> Review Published Dataset -> Select a published timetable

Changes to display data quality score with expected percentage values

---

config/settings/base.py

To resolve https://kpmgengineering.atlassian.net/browse/BODS-1770 on an interim basis - ticket must be raised to properly monitor dqms tasks

DQS_WAIT_TIMEOUT extended to 36 hrs

---

transit_odp/browse/views/local_authority.py

fix to display search items for autocomplete

fix to display search items for autocomplete

---

transit_odp/transmodel/models.py

changes to existing models required for timetable visualiser

changes to existing models required for timetable visualiser

---

transit_odp/pipelines/tests/test_naptan_etl/test_load.py

Fix for failing test case with regards to accessing location stops

Fix for failing test case with regards to accessing location stops

---

transit_odp/pipelines/pipelines/naptan_etl/load.py
transit_odp/pipelines/pipelines/naptan_etl/transform.py

updated method name to reflect standard naming conventions

updated method name to reflect standard naming conventions

---

transit_odp/pipelines/apps.py

minor fix to remove redundant import

minor fix to remove redundant import

---

transit_odp/common/utils/s3_bucket_connection.py
transit_odp/fares/tasks.py
transit_odp/fares/utils.py
transit_odp/timetables/utils.py

PR includes changes linked to:-
* https://kpmgengineering.atlassian.net/browse/BODS-2826

fix/BODS-2826:One-off Fares Task to rerun fares validator for a list of datasets from S3

---

transit_odp/timetables/extract.py

fix for an error when timetable visualiser flag is off

fix for an error when timetable visualiser flag is off

---

transit_odp/browse/templates/browse/timetables/dataset_detail/review_service_codes.html
transit_odp/publish/templates/publish/dataset_detail/review_service_codes.html
transit_odp/publish/templates/publish/revision_review/review_service_codes.html

This PR contains changes for [BODS-2903](https://kpmgengineering.atlassian.net/browse/BODS-2903)

BODS-2903 - unique combination of Service number (Line name)

---

transit_odp/pipelines/pipelines/dataset_etl/utils/transform.py
transit_odp/pipelines/tests/test_dataset_etl/data/test_non_operating_dates_exception/test_non_op_dates_exceptions_mixed.xml
transit_odp/pipelines/tests/test_dataset_etl/data/test_non_operating_dates_exception/test_non_op_dates_exceptions_only_services.xml
transit_odp/pipelines/tests/test_dataset_etl/data/test_operating_dates_exception/test_op_dates_exceptions.xml
transit_odp/pipelines/tests/test_dataset_etl/data/test_operating_profiles/test_operating_profiles_services.xml
transit_odp/pipelines/tests/test_dataset_etl/test_etl_non_operating_dates_exceptions.py
transit_odp/pipelines/tests/test_dataset_etl/test_etl_operating_dates_exceptions.py
transit_odp/pipelines/tests/test_dataset_etl/test_etl_operating_profiles.py
transit_odp/timetables/dataframes.py
transit_odp/timetables/transformers.py

Fix to load expected date values in exceptions table which fall within the operating period date range for each service
https://kpmgengineering.atlassian.net/browse/BODS-3268

fix for ensuring valid records within operating period dates are loaded

---

transit_odp/pipelines/pipelines/dataset_etl/utils/transform.py
transit_odp/pipelines/tests/test_dataset_etl/data/test_servicepatternstops/test_extract_sps_runtime_in_vj_timings.xml
transit_odp/pipelines/tests/test_dataset_etl/test_etl_service_pattern_stops.py
transit_odp/pipelines/tests/test_dataset_etl/test_etl_vehicle_journey.py
transit_odp/timetables/dataframes.py

changes to read wait time from vehicle journeys when available as per task
https://kpmgengineering.atlassian.net/browse/BODS-3747

changes to read wait time from vehicle journeys

---

transit_odp/pipelines/pipelines/dataset_etl/utils/dataframes.py
transit_odp/pipelines/pipelines/dataset_etl/utils/transform.py
transit_odp/pipelines/tests/test_dataset_etl/data/test_vehicle_journeys/test_vehicle_journeys_with_departure_day_shift.xml
transit_odp/pipelines/tests/test_dataset_etl/test_etl_service_pattern_stops.py
transit_odp/pipelines/tests/test_dataset_etl/test_etl_vehicle_journey.py
transit_odp/timetables/dataframes.py

changes to account for start dead run element

changes to account for start dead run element

---

transit_odp/pipelines/pipelines/dataset_etl/utils/transform.py

fix for incorrect stop sequence numbers when route links have different sequences mapped to it

fix for incorrect stop sequence numbers when route links have different sequences mapped to it

---

transit_odp/avl/post_publishing_checks/daily/tests/test_vehicle_journey_finder.py
transit_odp/avl/post_publishing_checks/daily/vehicle_journey_finder.py

The Changes are made as part of ticket [BODS-4504](https://kpmgengineering.atlassian.net/browse/BODS-4504)

[BODS-1720] logic to fetch only active dataset

---

transit_odp/browse/timetable_visualiser.py

This is to cover queryset change for AC3 in following ticket:-
https://kpmgengineering.atlassian.net/jira/software/c/projects/BODS/boards/1797?selectedIssue=BODS-4529

story/BODS-4529:: modified Django queryset to add operating date filter

---

transit_odp/pipelines/pipelines/dataset_etl/utils/dataframes.py
transit_odp/pipelines/tests/test_dataset_etl/test_etl_vehicle_journey.py
transit_odp/timetables/dataframes.py

changes to ensure dead run time is not added to vehicle journey time

changes to ensure dead run time is not added to vehicle journey time

---

transit_odp/pipelines/pipelines/dataset_etl/utils/transform.py

fix to memory leak issue when operating profiles and serviced orgs dataframes are merged

BODS-5259 - fix to memory leak issue

---

transit_odp/timetables/dataframes.py

fix for isodate issue with runtimes

fix for isodate issue with runtimes

---

transit_odp/data_quality/tasks.py
transit_odp/data_quality/tests/test_tasks.py

https://kpmgengineering.atlassian.net/browse/BODS-5755

[BODS-5755] stop inserting multiple entries in DataQualityTask

---

transit_odp/fares/forms.py
transit_odp/feedback/forms.py
transit_odp/publish/forms/dataset.py
transit_odp/templates/snippets/data_type_selector.html
transit_odp/templates/snippets/sidebar_related_links.html
transit_odp/users/forms/auth.py

This PR includes accessibility changes as below 
1. fix form elements missing label
2. fix heading level order

form element must have labels

---

transit_odp/avl/post_publishing_checks/daily/vehicle_journey_finder.py

PR includes following story
https://kpmgengineering.atlassian.net/browse/BODS-4392

[BODS-4392] updated return type to filtered values

---

config/settings/base.py
transit_odp/common/password_validation.py
transit_odp/common/tests/test_password_validation.py
transit_odp/users/tests/test_views.py
transit_odp/users/tests/test_views_auth.py

https://kpmgengineering.atlassian.net/jira/software/c/projects/BODS/boards/1975?selectedIssue=BODS-6129

[BODS-6129] Password Policy

---

transit_odp/frontend/assets/sass/components/select/_select.scss

https://kpmgengineering.atlassian.net/browse/BODS-6150

[BODS-6150] commented out css for select components

---

transit_odp/browse/templates/browse/disruptions/organisation/disruption_detail.html
transit_odp/browse/templates/browse/local_authority.html
transit_odp/browse/templates/browse/operators.html
transit_odp/browse/templates/browse/snippets/search_list.html
transit_odp/publish/templates/publish/dataset_detail/timetable_filters.html
transit_odp/site_admin/templates/site_admin/agent_list.html
transit_odp/site_admin/templates/site_admin/consumers/list.html
transit_odp/site_admin/templates/site_admin/header.html
transit_odp/site_admin/templates/site_admin/organisation_dataset_list/timetables.html
transit_odp/site_admin/templates/site_admin/organisation_list.html
transit_odp/templates/snippets/navlinks_data.html
transit_odp/templates/snippets/navlinks_publish.html

https://kpmgengineering.atlassian.net/browse/BODS-6183

[BODS-6183] added alt text for images tag

---

transit_odp/frontend/assets/sass/common.scss
transit_odp/guidance/templates/guidance/bus_operators/base.html
transit_odp/guidance/templates/guidance/developer/base.html
transit_odp/guidance/templates/guidance/local_authorities/base.html

https://kpmgengineering.atlassian.net/browse/BODS-6205

[BODS-6205] fix css for links in guidance pages

---

transit_odp/changelog/templates/changelog/snippets/release_notes.html

https://kpmgengineering.atlassian.net/browse/BODS-6239

[BODS-6239] Change log update 1.38

---

transit_odp/organisation/templates/organisation/snippets/organisation_profile_table.html

https://kpmgengineering.atlassian.net/browse/BODS-6244

[BODS-6244] ACCESSIBILITY - Manage organisation profile page

---

transit_odp/otc/common.py
transit_odp/otc/dataclasses.py
transit_odp/otc/tests/test_common.py
transit_odp/otc/tests/test_dataclasses.py

Reverts department-for-transport-BODS/bods#1351

[BODS-1580] Timetable data catalogue OTC Service Number column logic

---

transit_odp/avl/notifications.py
transit_odp/browse/views/local_authority.py
transit_odp/fares_validator/views/validation_messages.py
transit_odp/organisation/notifications.py
transit_odp/otc/querysets.py
transit_odp/pipelines/pipelines/dataset_etl/transform.py
transit_odp/publish/requires_attention.py
transit_odp/timetables/csv.py
transit_odp/timetables/transxchange.py

Reverts department-for-transport-BODS/bods#1467

Revert "story/BODS-6535: Remove redundant code"

---

transit_odp/browse/views/local_authority.py

Removed extra parameter

---

transit_odp/publish/requires_attention.py
transit_odp/publish/tests/test_require_attention.py

This PR includes changes for below tickets
https://kpmgengineering.atlassian.net/browse/BODS-7958
https://kpmgengineering.atlassian.net/browse/BODS-7960

[BODS-7958, BODS-7960] file selection logic, Compliance logic

---

transit_odp/browse/templates/browse/operators/operator_detail.html
transit_odp/common/constants.py

- Fix Fares SRA feature flag value
- Add percentage sign to fares services requiring attention
- Add feature flag to UI of Publish - Operator/Agent page
- Fix arguments of timeliness and compliance status' for overall and LTA reports

[Fares SRA] - Fixes to feature branch

---

transit_odp/browse/templates/browse/operators/operator_detail.html
transit_odp/fares/templates/fares/feed_list.html
transit_odp/fares/views/list.py

- Add feature flag to UI of Publish - Operator/Agent page

[Fares SRA]: Fix feature flagging - UI Publish - Operator/Agent page

---

.github/workflows/uat_deployment.yml

This reverts commit d53b6e94b6f7f9ef3a33d04ad529ee5040953143.
Now that the UAT is back up and running in non-prod, introducing the UAT back in here

Revert "BODS-8085: Disable UAT deployment temporarily"

---

transit_odp/browse/lta_column_headers.py
transit_odp/organisation/csv/service_codes.py

Includes: https://kpmgengineering.atlassian.net/browse/BODS-8814

fix/BODS-8814: Fix 'Registration Status' column in LTA and operator reports

---

transit_odp/avl/post_publishing_checks/daily/tests/test_vehicle_journey_finder.py
transit_odp/avl/post_publishing_checks/daily/vehicle_journey_finder.py

Includes: https://kpmgengineering.atlassian.net/browse/BODS-8568

story/BODS-8568: Update PPC logic to handle where data for NOC and Line is for a different registration

---

transit_odp/browse/views/local_authority.py
transit_odp/templates/account/email_confirm.html
transit_odp/timetables/views/review.py

Following issues were fixed in this PR
https://kpmgengineering.atlassian.net/browse/BODS-9577
https://kpmgengineering.atlassian.net/browse/BODS-9576
https://kpmgengineering.atlassian.net/browse/BODS-9575

[Bugs/bods-9576] - Fixed issues with 500 error
